# SITE CONFIGURATION
baseurl: ""
url: "http://rrogoda.pl"
language: "pl"
description: "Osobista strona internetowa, na której prezentuje swoje umiejętności oraz dzielę się zdobytą wiedzą." # used by search engines
title: "Programowanie"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: "Rafał Rogoda"

  avatar: assets/img/LOGO.png
  favicon: assets/favicon/favicon.ico
  gravatar: # Email MD5 hash
  description: "Osobista strona internetowa, na której prezentuje swoje umiejętności oraz dzielę się zdobytą wiedzą." # used by search engines

  # Header and footer text
  header_text: > #two or three lines to describe your site
    <h1><br>Blog na temat programowania<br><br><br><br></h1> 
  header_text_feature_image: assets/img/blog/feature-img.jpeg
  footer_text: >
   <p class="font-footer text-success">Można mnie również znaleźć na:</p>

  # Icons
  rss: true  # Make sure you created a feed.xml with feed.xml layout
  email_address: rafal.rogoda@gmail.com
  behance:
  bitbucket:
  dribbble:
  facebook: rafal.rogoda
  flickr:
  gitlab:
  github: "Rogoda"
  google_plus:
  instagram:
  keybase:
  linkedin:  https://www.linkedin.com/in/rafa%C5%82-rogoda-53771990/
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: # "twitter username"
  vimeo:
  wordpress:
  youtube:

  # Scripts / Features 
  google_analytics: "UA-124595820-1"
  disqus_shortname: "rrogoda"
  katex: true # Enable if using math markup
  portfolio: true
  search: true
  tags: true
  blog: true
  hobby: true
  
  # Localization strings
  str_follow_on: "Śledź na"
  str_rss_follow: "RSS"
  str_email: "Email"
  str_next_post: "Następny post"
  str_previous_post: "Poprzedni post"
  str_next_page: "Starsze posty"
  str_previous_page: "Nowsze posty"
  str_continue_reading: "Kontynuuj czytanie"
  str_javascript_required_disqus: "Proszę, włącz JavaScript, aby zobaczyć komentarze"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Fira+Mono&subset=latin,latin-ext"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# INTERESTS
interests: [
  {title: "Programowanie",
  url: /zainteresowania/programowanie,
  img: ../assets/img/interests/programming/feature-img-min.jpeg
  },
  {title: "Gra giełdowa",
  url: /zainteresowania/gielda,
  img: ../assets/img/interests/market/feature-img-min.jpeg
  },
  {title: "Motywacja",
  url: /zainteresowania/motywacja,
  img: ../assets/img/interests/motivation/feature-img-min.jpeg
  }]
collections:
  default:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap, jekyll-minifier]
#theme: type-on-strap # Uncomment if using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png"]
