---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _default
  label: Default
  create: all
  match: "**/*"
upload_dir: assets/img/drafts
public_path: "/assets/img/posts"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:filename:"
